### ISSUE TITLE
oauth by google groups

### ISSUE THREAD

**Issue by cemo** [halkeye/proxy-s3-google-oauth#69]
Hi, First of all thanks for sharing project. I would like to authenticate our users by using google groups. I mean users who are member of a particular google group can access the data in a bucket?

**Comment by halkeye** [comment]
Sorry, I don't know of any way to support that as the code stands right
now. I'm sure there are APIs for it.

I have since left the company I created this for so I don't foresee much
development on my part

**Comment by cemo** [comment]
Thanks
