### ISSUE TITLE
Support for ephemeral credentials

### ISSUE THREAD

**Issue by bwalding** [halkeye/proxy-s3-google-oauth#71]
One limitation that you may face is in locked down corporate environments - e.g. a policy that by default blocks the creation of IAM users and static credentials (static credentials are typically not rotated frequently, and if they're compromised may not be revoked in a timely fashion).

The AWS solution for this is ephemeral credentials supplied by the "infrastructure" (instance metadata if running natively on an instance, or a task role if running inside a container on ECS, kube2iam is another source of credentials in a k8s environment).

In those cases, I would suggest letting your proxy code leverage the AWS library for S3 to acquire the relevant AWS credentials.  If you find yourself trying to implement this yourself then you've gone down the wrong path - there are key expiry issues, multiple token sources etc to consider - the libraries will do it.

I suspect you just need to only supply the `AWS_ACCESS_KEY_ID` etc if it is provided - and rely on a task role automatically being picked up if it's not -
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-node.html

**Comment by halkeye** [comment]
okay I've removed the requirement on those two env arguments. But I don't have something handy to test while being hosted on aws. If you get a chance to test it then \o/, but i'll try to set something up and test later in the week.

**Comment by halkeye** [comment]
So fixed with #14865edb56cf6a557d36f806ab9de15d6d978d9a

Auto build the image, https://hub.docker.com/r/halkeye/proxy-s3-google-oauth
